"""
Concrete prompt template for critique tasks.
Used when the assistant is asked to evaluate and provide constructive feedback.
"""

from metis.prompts.templates.base_prompt_template import BasePromptTemplate

class CritiquePrompt(BasePromptTemplate):
    """
    Builds a prompt for critiquing an idea, response, or user-generated content.
    """

    def __init__(self, context: str, tool_output: str = "", tone: str = "Analytical", persona: str = "Critical Reviewer"):
        super().__init__()
        self.context = context
        self.tool_output = tool_output
        self.tone = tone
        self.persona = persona

    def set_tone(self):
        # Set tone and persona appropriate for constructive critique
        self.prompt.tone = self.tone
        self.prompt.persona = self.persona

    def add_task_instruction(self):
        # Instruct the model to evaluate the provided content
        self.prompt.task = "Critique the content with constructive feedback and suggestions."

    def inject_context(self):
        # Provide the item or subject to be critiqued
        self.prompt.context = self.context

    def inject_tool_output(self):
        # Include any analysis or metrics generated by supporting tools
        self.prompt.tool_output = self.tool_output