"""
DefaultPromptBuilder constructs a Prompt instance using basic input components.
Follows the Builder pattern to enable fluent prompt assembly.
"""

from metis.prompts.prompt import Prompt

class DefaultPromptBuilder:
    """
    A flexible prompt builder that assembles a Prompt object step-by-step.
    Used when no model-specific formatting is required.
    """

    def __init__(self):
        self._prompt = Prompt()

    def add_tone(self, tone: str, persona: str):
        # Set the system tone and persona
        self._prompt.tone = tone
        self._prompt.persona = persona
        return self

    def add_task_instruction(self, task: str):
        # Define the prompt's goal or intent
        self._prompt.task = task
        return self

    def add_context(self, memory: str):
        # Add conversation memory or background knowledge
        self._prompt.context = memory
        return self

    def add_tool_output(self, tool_output: str):
        # Inject any information generated by tools or plugins
        self._prompt.tool_output = tool_output
        return self

    def set_user_input(self, user_input: str):
        # Store the user's current input or question
        self._prompt.user_input = user_input
        return self

    def build(self) -> Prompt:
        # Return the fully assembled prompt object
        return self._prompt